export const UPLOAD_PROFILEIMAGE = 'UPLOAD_PROFILEIMAGE';
export const RESPONSE_UPLOAD_PROFILEIMAGE = 'RESPONSE_UPLOAD_PROFILEIMAGE';
export const RESPONSE_ERROR_UPLOAD_PROFILEIMAGE = 'RESPONSE_ERROR_UPLOAD_PROFILEIMAGE';